#set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk100mhz]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN E3 [get_ports clk100mhz]
set_property PACKAGE_PIN N17 [get_ports rst]
##Switches

set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {sw[0]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {sw[1]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {sw[2]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {sw[3]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {sw[4]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {sw[5]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {sw[6]}]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {sw[7]}]
set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVCMOS18} [get_ports {sw[8]}]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS18} [get_ports {sw[9]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {sw[10]}]
set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVCMOS33} [get_ports {sw[11]}]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {sw[12]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {sw[13]}]
set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVCMOS33} [get_ports {sw[14]}]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {sw[15]}]
#7 segment display

set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {o_seg[0]}]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports {o_seg[1]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {o_seg[2]}]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {o_seg[3]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {o_seg[4]}]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {o_seg[5]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {o_seg[6]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {o_seg[7]}]

set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {o_sel[0]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {o_sel[1]}]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {o_sel[2]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {o_sel[3]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {o_sel[4]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {o_sel[5]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {o_sel[6]}]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {o_sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN V11 [get_ports {led[15]}]
set_property PACKAGE_PIN V12 [get_ports {led[14]}]
set_property PACKAGE_PIN V14 [get_ports {led[13]}]
set_property PACKAGE_PIN V15 [get_ports {led[12]}]
set_property PACKAGE_PIN T16 [get_ports {led[11]}]
set_property PACKAGE_PIN U14 [get_ports {led[10]}]
set_property PACKAGE_PIN T15 [get_ports {led[9]}]
set_property PACKAGE_PIN V16 [get_ports {led[8]}]
set_property PACKAGE_PIN U16 [get_ports {led[7]}]
set_property PACKAGE_PIN U17 [get_ports {led[6]}]
set_property PACKAGE_PIN V17 [get_ports {led[5]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property PACKAGE_PIN H17 [get_ports {led[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports enter_break]
#set_property IOSTANDARD LVCMOS33 [get_ports enter_sys]
#set_property IOSTANDARD LVCMOS33 [get_ports enter_teq]
#set_property PACKAGE_PIN J13 [get_ports enter_break]
#set_property PACKAGE_PIN K15 [get_ports enter_sys]
#set_property PACKAGE_PIN H17 [get_ports enter_teq]
set_property CLOCK_DEDICAGTED_ROUTE FALSE[get_nets rst_IBUF]
#set_property CLOCK_DEDICAGTED_ROUTE FALSE[get_nets sw_IBUF[6]]
#set_property CLOCK_DEDICAGTED_ROUTE FALSE[get_nets sw_IBUF[5]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[0]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[1]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[2]]
set_property IOSTANDARD LVCMOS33 [get_ports btn[3]]
set_property PACKAGE_PIN M18 [get_ports btn[0]]
set_property PACKAGE_PIN P18 [get_ports btn[1]]
set_property PACKAGE_PIN P17 [get_ports btn[2]]
set_property PACKAGE_PIN M17 [get_ports btn[3]]
#set_property CLOCK_DEDICAGTED_ROUTE FALSE[get_nets btn_IBUF[0]]
#set_property CLOCK_DEDICAGTED_ROUTE FALSE[get_nets clk100mhz_in_IBUF]
set_property IOSTANDARD LVCMOS33 [get_ports {SD_DAT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SD_DAT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SD_DAT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SD_DAT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SD_CD]
set_property IOSTANDARD LVCMOS33 [get_ports SD_CMD]
set_property IOSTANDARD LVCMOS33 [get_ports SD_RESET]
set_property IOSTANDARD LVCMOS33 [get_ports SD_SCK]
set_property PACKAGE_PIN A1 [get_ports SD_CD]
set_property PACKAGE_PIN C1 [get_ports SD_CMD]
set_property PACKAGE_PIN E2 [get_ports SD_RESET]
set_property PACKAGE_PIN B1 [get_ports SD_SCK]
set_property PACKAGE_PIN C2 [get_ports {SD_DAT[0]}]
set_property PACKAGE_PIN E1 [get_ports {SD_DAT[1]}]
set_property PACKAGE_PIN F1 [get_ports {SD_DAT[2]}]
set_property PACKAGE_PIN D2 [get_ports {SD_DAT[3]}]