# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Mips54_LoadBoard.xdc

# IP: ip/SDTrans/SDTrans.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SDTrans || ORIG_REF_NAME==SDTrans} -quiet] -quiet

# IP: ip/ddr2_ram/ddr2_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr2_ram || ORIG_REF_NAME==ddr2_ram} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: ip/cache/cache.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cache || ORIG_REF_NAME==cache} -quiet] -quiet
